In [4]:
import numpy as np

In [13]:
mylist = (2, 4, 5, 6, 7, 9, 7, 8, 10)
mya = np.array(mylist)
print(mya.dtype)
mya.size


int32


9

In [11]:
np.mean(mya)

6.444444444444445

In [14]:
print(mya.mean())
mya.sum()

6.444444444444445


58

In [21]:
print(np.max(mya))
print(np.min(mya))
print(np.argmin(mya))
print(np.argmax(mya))
print(np.sum(mya))
print(np.mean(mya))
print(np.std(mya))
print(np.median(mya))
print(mylist)
print(np.sort(mya))

10
2
0
8
58
6.444444444444445
2.3622546250521443
7.0
(2, 4, 5, 6, 7, 9, 7, 8, 10)
[ 2  4  5  6  7  7  8  9 10]
6.444444444444445


Numpy Operators

In [22]:
new_mya = np.copy(mya)
new_mya

array([ 2,  4,  5,  6,  7,  9,  7,  8, 10])

In [23]:
# Element-wise addition
mya + new_mya

array([ 4,  8, 10, 12, 14, 18, 14, 16, 20])

In [24]:
mya - new_mya

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
print(np.ones(10))
print(np.zeros(5))
print(np.eye(3,7))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]


SLICING

In [32]:
print(mya)
print(mya[1:5])
mya[6:10]

[ 2  4  5  6  7  9  7  8 10]
[4 5 6 7]


array([ 7,  8, 10])