In [1]:
import numpy as np

In [2]:
pwd

'C:\\Users\\j\\Documents\\DS Projects\\Gazal'

In [20]:
# create a  list
mylist = [1,2,30,40,-50]
sh = myarr.shape
print(type(mylist))
mylist

<class 'list'>


[1, 2, 30, 40, -50]

In [29]:
# from list create array
myarr = np.array(mylist)
print(myarr)
print(mylist)
print(myarr.dtype)
print(myarr.shape)
print(myarr.size)
print(myarr.item)
print(myarr.itemsize)
print(type(myarr))
print(type(sh))
myarr.itemsize
print(sh[0])


[  1   2  30  40 -50]
[1, 2, 30, 40, -50]
int32
(5,)
5
<built-in method item of numpy.ndarray object at 0x00000217625A10B0>
4
<class 'numpy.ndarray'>
<class 'tuple'>
5


2 dimensional matrix

In [34]:
# Create a 2D array (matrix)
a = [2, 4]
b = [3, 5]
mat1 = np.array([[a],[b]])
mat2 = np.array([[1, 2], [3, 4]])
c = mat1*mat2
print(mat1.T)
print(mat2.T)
print(c)

[[[2 3]]

 [[4 5]]]
[[1 3]
 [2 4]]
[[[ 2  8]
  [ 6 16]]

 [[ 3 10]
  [ 9 20]]]


In [35]:
print(mat1.dtype)
print(mat1.shape)
print(mat1.size)
print(mat1.item)
print(mat1.itemsize)


int32
(2, 1, 2)
4
<built-in method item of numpy.ndarray object at 0x00000217625A07B0>
4
[[[ 2  8]
  [ 6 16]]

 [[ 3 10]
  [ 9 20]]]


In [36]:
print(c)
print(c.dtype)
print(c.shape)
print(c.size)
print(c.item)
print(c.itemsize)

[[[ 2  8]
  [ 6 16]]

 [[ 3 10]
  [ 9 20]]]
int32
(2, 2, 2)
8
<built-in method item of numpy.ndarray object at 0x00000217625A3750>
4
